# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# Chargement des contr√¥leurs (attributs) - inclut src/Controller et sous-dossiers (Api, etc.)
controllers:
<<<<<<< HEAD
    resource:
        path: ../src/Controller/
        namespace: App\Controller
=======
    resource: ../src/Controller/
>>>>>>> origin/Evenement-oussema
    type: attribute
